// <auto-generated />
namespace University.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TeacherManyToManyFixed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TeacherManyToManyFixed));
        
        string IMigrationMetadata.Id
        {
            get { return "202110172054327_TeacherManyToManyFixed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
